name: CI
run-name: ${{ github.actor }} pushed a commit

on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm install

      - name: prettier
        run: npx prettier --check .

      - name: test
        run: npm run test

      - name: build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish on GitHub Pages
        run: npm run publish

      - name: Deploy
        run: |
          git config --global user.name "${github.actor}"
          git config --global user.email "${github.actor}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
