name: CI
run-name: ${{ github.actor }} push | ${{ github.ref }}

on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Prettier
        run: npx prettier --check .

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish on GitHub Pages
        run: npm run deploy
