name: CI
run-name: ${{ github.actor }} push | pull_request

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm install

      - name: prettier
        run: npx prettier --check .

      - name: test
        run: npm run test

      - name: build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy app
        run: exit 0
