name: CI
run-name: ${{ github.actor }} push | pull_request

on:
  push:
    branches:
      - "YOUR-TEST-BRANCH"
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy app
        run: exit 0
