name: learn-github-actions
run-name: ${{ github.actor }} created or edited a pull request
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm install

      - name: prettier
        run: npx prettier --check .

      - name: test
        run: npm run test

      - name: build
        run: npm run build
